// Generated by CoffeeScript 1.7.1
(function() {
  var GPA;

  GPA = require('../schemas/schemas').GPA;

  exports.edit = function(req, res) {
    var id, newSection, section;
    section = req.body;
    delete section._id;
    id = req.params.id;
    Section.update({
      _id: id
    }, {
      $set: section
    }, function(err, numAffected, raw) {
      if (err) {
        console.log(err);
      }
      console.log('The number of updated documents was %d', numAffected);
      return res.send(section);
    });
    exports.create = function(req, res) {};
    newSection = new Section(req.body);
    console.log('created section ' + newSection.title);
    newSection.save();
    return res.send();
  };

}).call(this);

//# sourceMappingURL=gpa.map
